name: PwingSkriptAddon
version: 1.0.2
main: com.pwing.pwingskriptaddon.PwingSkriptAddon
api-version: '1.16'
depend: [Skript]
commands:
  biomebrush:
    description: Give and use biome brush tool
    usage: /biomebrush give <biome> [radius]
    permission: pwingskriptaddon.biomebrush
    permission-message: You don't have permission to use this command.
libraries:
  - net.kyori:adventure-api:4.14.0
  - net.kyori:adventure-text-minimessage:4.14.0
  - net.kyori:adventure-platform-bukkit:4.3.0
description: An addon for PwingSkript that provides additional syntax and functionality.
author: finder17
permissions:
  pwingskriptaddon.biomebrush:
    description: Allows use of the /biomebrush command and biome brush tool
    default: op
